### ISSUE TITLE
[BUG] Shuffle button generates lag

### ISSUE THREAD

**Issue by Altarentys** [theovilardo/PixelPlayer#628]
Hi!
When clicking the shuffle button in the player it generates lag as you can see on the video attached ; when shuffle is clicked, the seekbar animation and the timestamp pause for a moment.

https://github.com/user-attachments/assets/03bd134c-a030-4d75-ad01-b01c1a54606d

**Comment by lostf1sh** [comment]
i mean the buttons shouldnt be even look like this, ive never seen this, but yeah shuffle lag is also fixed in the new update

![Screenshot_20251224_072346_PixelPlayer.jpg](https://github.com/user-attachments/assets/d2d6ebc9-feaf-47e1-857d-589fc4240cca)

**Comment by Altarentys** [comment]
> i mean the buttons shouldnt be even look like this, ive never seen this, but yeah shuffle lag is also fixed in the new update
> 
> ![Screenshot_20251224_072346_PixelPlayer.jpg](https://github.com/user-attachments/assets/d2d6ebc9-feaf-47e1-857d-589fc4240cca)

Oh this is strange, might be linked with another issue I have #626 where the app isn't filling all the space to the bottom of the screen...
As for shuffling lag, I'm already running latest version and I still experience lag...

**Comment by ThatFluffyJello** [comment]
Just got this issue too, I'm guessing it's a shuffling issue since I have a decently large FLAC library. I tapped on the shuffle button a few times, no visual artifacts just straight up lag and the app crashed a few seconds later. I tried opening the app again, selected the same song to play and tapped the shuffle button once, 3ish second lag but then it shuffled properly.

**Comment by lostf1sh** [comment]
> Just got this issue too, I'm guessing it's a shuffling issue since I have a decently large FLAC library. I tapped on the shuffle button a few times, no visual artifacts just straight up lag and the app crashed a few seconds later. I tried opening the app again, selected the same song to play and tapped the shuffle button once, 3ish second lag but then it shuffled properly.

thats happening because it just ''really' shuffling, like cards, As the song queue grows, the shuffle speed will slow down accordingly. In the upcoming update and future updates, we will strive to ensure that shuffle is performed in the most efficient manner.

**Comment by lostf1sh** [comment]
Duplicate of #543 — all describe lag/momentary playback freeze/animation stutter when tapping shuffle. Closing in favor of the canonical issue, please follow #543 for updates.
